DROP VIEW IF EXISTS {schema}.coecoclass_component_wgt;
CREATE VIEW {schema}.coecoclass_component_wgt AS
WITH base AS (
SELECT b.muacres, b.muacres * (a.comppct_r / 100.0) comp_ac, a.*
  FROM {schema}.component_detail a
  LEFT JOIN mapunit b USING (mukey)

), wgt_avg AS ( 
SELECT ecoclassid_std, max(ecoclassid) ecoclassid, max(ecoclassname) ecoclassname,
       round((sum(slope_l::float * comp_ac)/sum(comp_ac))::numeric, 0) slope_l, 
       round((sum(slope_r::float * comp_ac)/sum(comp_ac))::numeric, 0) slope_r, 
       round((sum(slope_h::float * comp_ac)/sum(comp_ac))::numeric, 0) slope_h, 
       round((sum(slopelenusle_l::float * comp_ac)/sum(comp_ac))::numeric, 0) slopelenusle_l, 
       round((sum(slopelenusle_r::float * comp_ac)/sum(comp_ac))::numeric, 0) slopelenusle_r, 
       round((sum(slopelenusle_h::float * comp_ac)/sum(comp_ac))::numeric, 0) slopelenusle_h, 
       round((sum(tfact::float * comp_ac)/sum(comp_ac))::numeric, 0) tfact, 
       round((sum(elev_l::float * comp_ac)/sum(comp_ac))::numeric, 0) elev_l, 
       round((sum(elev_r::float * comp_ac)/sum(comp_ac))::numeric, 0) elev_r, 
       round((sum(elev_h::float * comp_ac)/sum(comp_ac))::numeric, 0) elev_h, 
       round((sum(aspectccwise::float * comp_ac)/sum(comp_ac))::numeric, 0) aspectccwise, 
       round((sum(aspectrep::float * comp_ac)/sum(comp_ac))::numeric, 0) aspectrep, 
       round((sum(aspectcwise::float * comp_ac)/sum(comp_ac))::numeric, 0) aspectcwise,
       round((sum(albedodry_l::float * comp_ac)/sum(comp_ac))::numeric, 2) albedodry_l, 
       round((sum(albedodry_r::float * comp_ac)/sum(comp_ac))::numeric, 2) albedodry_r, 
       round((sum(albedodry_h::float * comp_ac)/sum(comp_ac))::numeric, 2) albedodry_h, 
       round((sum(airtempa_l::float * comp_ac)/sum(comp_ac))::numeric, 1) airtempa_l, 
       round((sum(airtempa_r::float * comp_ac)/sum(comp_ac))::numeric, 1) airtempa_r, 
       round((sum(airtempa_h::float * comp_ac)/sum(comp_ac))::numeric, 1) airtempa_h, 
       round((sum(map_l::float * comp_ac)/sum(comp_ac))::numeric, 0) map_l,
       round((sum(map_r::float * comp_ac)/sum(comp_ac))::numeric, 0) map_r, 
       round((sum(map_h::float * comp_ac)/sum(comp_ac))::numeric, 0) map_h, 
       round((sum(reannualprecip_l::float * comp_ac)/sum(comp_ac))::numeric, 0) reannualprecip_l, 
       round((sum(reannualprecip_r::float * comp_ac)/sum(comp_ac))::numeric, 0) reannualprecip_r, 
       round((sum(reannualprecip_h::float * comp_ac)/sum(comp_ac))::numeric, 0) reannualprecip_h, 
       round((sum(ffd_l::float * comp_ac)/sum(comp_ac))::numeric, 0) ffd_l, 
       round((sum(ffd_r::float * comp_ac)/sum(comp_ac))::numeric, 0) ffd_r,
       round((sum(ffd_h::float * comp_ac)/sum(comp_ac))::numeric, 0) ffd_h, 
       round((sum(cropprodindex::float * comp_ac)/sum(comp_ac))::numeric, 0) cropprodindex, 
       round((sum(rsprod_l::float * comp_ac)/sum(comp_ac))::numeric, 0) rsprod_l,
       round((sum(rsprod_r::float * comp_ac)/sum(comp_ac))::numeric, 0) rsprod_r, 
       round((sum(rsprod_h::float * comp_ac)/sum(comp_ac))::numeric, 0) rsprod_h, 
       round((sum(initsub_l::float * comp_ac)/sum(comp_ac))::numeric, 0) initsub_l, 
       round((sum(initsub_r::float * comp_ac)/sum(comp_ac))::numeric, 0) initsub_r, 
       round((sum(initsub_h::float * comp_ac)/sum(comp_ac))::numeric, 0) initsub_h,
       round((sum(totalsub_l::float * comp_ac)/sum(comp_ac))::numeric, 0) totalsub_l, 
       round((sum(totalsub_r::float * comp_ac)/sum(comp_ac))::numeric, 0) totalsub_r, 
       round((sum(totalsub_h::float * comp_ac)/sum(comp_ac))::numeric, 0) totalsub_h, 
       round((sum(castorieindex::float * comp_ac)/sum(comp_ac))::numeric, 0) castorieindex, 
       round((sum(ph1to1h2o_l::float * comp_ac)/sum(comp_ac))::numeric, 1) ph1to1h2o_l, 
       round((sum(ph1to1h2o_r::float * comp_ac)/sum(comp_ac))::numeric, 1) ph1to1h2o_r, 
       round((sum(ph1to1h2o_h::float * comp_ac)/sum(comp_ac))::numeric, 1) ph1to1h2o_h
  FROM base
 GROUP BY ecoclassid_std

), cat_grp AS (
SELECT ecoclassid_std, max(ecoclassid) ecoclassid, max(ecoclassname) ecoclassname,
       string_agg(distinct compname, ', ' order by compname) compname, 
       string_agg(distinct runoff, ', ' order by runoff) runoff,
       string_agg(distinct wei, ', ' order by wei) wei,
       string_agg(distinct weg, ', ' order by weg) weg,
       string_agg(distinct erocl, ', ' order by erocl) erocl,
       string_agg(distinct earthcovkind1, ', ' order by earthcovkind1) earthcovkind1,
       string_agg(distinct earthcovkind2, ', ' order by earthcovkind2) earthcovkind2,
       string_agg(distinct hydricon, ', ' order by hydricon) hydricon,
       string_agg(distinct hydricrating, ', ' order by hydricrating) hydricrating,
       string_agg(distinct drainagecl, ', ' order by drainagecl) drainagecl,
       string_agg(distinct geomdesc, ', ' order by geomdesc) geomdesc,
       string_agg(distinct nirrcapcl, ', ' order by nirrcapcl) nirrcapcl,
       string_agg(distinct nirrcapscl, ', ' order by nirrcapscl) nirrcapscl,
       string_agg(distinct nirrcapunit::varchar, ', ' order by nirrcapunit::varchar) nirrcapunit,
       string_agg(distinct irrcapcl, ', ' order by irrcapcl) irrcapcl,
       string_agg(distinct irrcapscl, ', ' order by irrcapscl) irrcapscl,
       string_agg(distinct irrcapunit::varchar, ', ' order by irrcapunit::varchar) irrcapunit,
       string_agg(distinct constreeshrubgrp, ', ' order by constreeshrubgrp) constreeshrubgrp,
       string_agg(distinct wndbrksuitgrp, ', ' order by wndbrksuitgrp) wndbrksuitgrp,
       string_agg(distinct foragesuitgrpid, ', ' order by foragesuitgrpid) foragesuitgrpid,
       string_agg(distinct wlgrain, ', ' order by wlgrain) wlgrain,
       string_agg(distinct wlgrass, ', ' order by wlgrass) wlgrass,
       string_agg(distinct wlherbaceous, ', ' order by wlherbaceous) wlherbaceous,
       string_agg(distinct wlshrub, ', ' order by wlshrub) wlshrub,
       string_agg(distinct wlconiferous, ', ' order by wlconiferous) wlconiferous,
       string_agg(distinct wlhardwood, ', ' order by wlhardwood) wlhardwood,
       string_agg(distinct wlwetplant, ', ' order by wlwetplant) wlwetplant,
       string_agg(distinct wlshallowwat, ', ' order by wlshallowwat) wlshallowwat,
       string_agg(distinct wlrangeland, ', ' order by wlrangeland) wlrangeland,
       string_agg(distinct wlopenland, ', ' order by wlopenland) wlopenland,
       string_agg(distinct wlwoodland, ', ' order by wlwoodland) wlwoodland,
       string_agg(distinct wlwetland, ', ' order by wlwetland) wlwetland,
       string_agg(distinct soilslippot, ', ' order by soilslippot) soilslippot,
       string_agg(distinct frostact, ', ' order by frostact) frostact,
       string_agg(distinct hydgrp, ', ' order by hydgrp) hydgrp,
       string_agg(distinct corcon, ', ' order by corcon) corcon,
       string_agg(distinct corsteel, ', ' order by corsteel) corsteel,
       string_agg(distinct taxclname, '; ' order by taxclname) taxclname,
       string_agg(distinct taxorder, ', ' order by taxorder) taxorder,
       string_agg(distinct taxsuborder, ', ' order by taxsuborder) taxsuborder,
       string_agg(distinct taxgrtgroup, ', ' order by taxgrtgroup) taxgrtgroup,
       string_agg(distinct taxsubgrp, ', ' order by taxsubgrp) taxsubgrp,
       string_agg(distinct taxpartsize, ', ' order by taxpartsize) taxpartsize,
       string_agg(distinct taxpartsizemod, ', ' order by taxpartsizemod) taxpartsizemod,
       string_agg(distinct taxceactcl, ', ' order by taxceactcl) taxceactcl,
       string_agg(distinct taxreaction, ', ' order by taxreaction) taxreaction,
       string_agg(distinct taxtempcl, ', ' order by taxtempcl) taxtempcl,
       string_agg(distinct taxmoistscl, ', ' order by taxmoistscl) taxmoistscl,
       string_agg(distinct taxmoistcl, ', ' order by taxmoistcl) taxmoistcl,
       string_agg(distinct taxtempregime, ', ' order by taxtempregime) taxtempregime,
       string_agg(distinct soiltaxedition, ', ' order by soiltaxedition) soiltaxedition,
       string_agg(distinct flecolcomnum, ', ' order by flecolcomnum) flecolcomnum,
       string_agg(distinct flhe, ', ' order by flhe) flhe,
       string_agg(distinct flphe, ', ' order by flphe) flphe,
       string_agg(distinct flsoilleachpot, ', ' order by flsoilleachpot) flsoilleachpot,
       string_agg(distinct flsoirunoffpot, ', ' order by flsoirunoffpot) flsoirunoffpot,
       string_agg(distinct fltemik2use, ', ' order by fltemik2use) fltemik2use,
       string_agg(distinct fltriumph2use, ', ' order by fltriumph2use) fltriumph2use,
       string_agg(distinct indraingrp, ', ' order by indraingrp) indraingrp,
       string_agg(distinct innitrateleachi::varchar, ', ' order by innitrateleachi::varchar) innitrateleachi,
       string_agg(distinct misoimgmtgrp, ', ' order by misoimgmtgrp) misoimgmtgrp,
       string_agg(distinct vasoimgtgrp, ', ' order by vasoimgtgrp) vasoimgtgrp,
       string_agg(distinct texdesc, '; ' order by texdesc) texdesc,
       string_agg(distinct texcl, ', ' order by texcl) texcl,
       string_agg(distinct pmgroupname, '; ' order by pmgroupname) pmgroupname
  FROM base
 GROUP BY ecoclassid_std
)

SELECT a.*,
       b.compname, b.runoff, b.wei, b.weg, b.erocl, b.earthcovkind1, b.earthcovkind2,
       b.hydricon, b.hydricrating, b.drainagecl,
       array_to_string(
         array(
           SELECT DISTINCT g
           FROM unnest(regexp_split_to_array(b.geomdesc, ', *')) AS g 
           WHERE g NOT LIKE '%Error in Exists On%'                  
           ORDER BY g), ', ') geomdesc,
       b.nirrcapcl, b.nirrcapscl,
       b.nirrcapunit, b.irrcapcl, b.irrcapscl, b.irrcapunit,
       b.constreeshrubgrp, b.wndbrksuitgrp, b.foragesuitgrpid, b.wlgrain, b.wlgrass,
       b.wlherbaceous, b.wlshrub, b.wlconiferous, b.wlhardwood, b.wlwetplant,
       b.wlshallowwat, b.wlrangeland, b.wlopenland, b.wlwoodland, b.wlwetland,
       b.soilslippot, b.frostact, b.hydgrp, b.corcon, b.corsteel, 
       b.taxclname, b.taxorder, b.taxsuborder, b.taxgrtgroup, b.taxsubgrp,
       b.taxpartsize, b.taxpartsizemod, b.taxceactcl, b.taxreaction,
       b.taxtempcl, b.taxmoistscl, b.taxmoistcl, b.taxtempregime, b.soiltaxedition,
       b.flecolcomnum, b.flhe, b.flphe, b.flsoilleachpot, b.flsoirunoffpot,
       b.fltemik2use, b.fltriumph2use, b.indraingrp, b.innitrateleachi,
       b.misoimgmtgrp, b.vasoimgtgrp, b.texdesc, b.texcl, b.pmgroupname
  FROM wgt_avg a
 INNER JOIN cat_grp b USING (ecoclassid_std)   
  
