DROP VIEW IF EXISTS soil.ecogroup_component_wgt;
CREATE VIEW soil.ecogroup_component_wgt AS
WITH base AS (
SELECT coalesce(b.ecogroup, a.ecoclassid_std) ecogroup,
       coalesce(c.groupname, a.ecoclassname) groupname,
	   (a.comppct_r / 100.0) * d.area_ha eco_ha,
	   a.*
  FROM soil.component_detail a
  LEFT JOIN soil.ecogroup b ON a.ecoclassid_std = b.ecoid
  LEFT JOIN soil.ecogroup_meta c ON b.ecogroup = c.ecogroup
  LEFT JOIN soil.mupolygon d ON a.mukey = d.mukey

), base_real  AS (
SELECT ecogroup, groupname,
       round((sum(slope_l::float * eco_ha)/sum(eco_ha))::numeric, 0) slope_l, 
       round((sum(slope_r::float * eco_ha)/sum(eco_ha))::numeric, 0) slope_r, 
       round((sum(slope_h::float * eco_ha)/sum(eco_ha))::numeric, 0) slope_h, 
       round((sum(slopelenusle_l::float * eco_ha)/sum(eco_ha))::numeric, 0) slopelenusle_l, 
       round((sum(slopelenusle_r::float * eco_ha)/sum(eco_ha))::numeric, 0) slopelenusle_r, 
       round((sum(slopelenusle_h::float * eco_ha)/sum(eco_ha))::numeric, 0) slopelenusle_h, 
       round((sum(tfact::float * eco_ha)/sum(eco_ha))::numeric, 0) tfact, 
       round((sum(elev_l::float * eco_ha)/sum(eco_ha))::numeric, 0) elev_l, 
       round((sum(elev_r::float * eco_ha)/sum(eco_ha))::numeric, 0) elev_r, 
       round((sum(elev_h::float * eco_ha)/sum(eco_ha))::numeric, 0) elev_h, 
       round((sum(aspectccwise::float * eco_ha)/sum(eco_ha))::numeric, 0) aspectccwise, 
       round((sum(aspectrep::float * eco_ha)/sum(eco_ha))::numeric, 0) aspectrep, 
       round((sum(aspectcwise::float * eco_ha)/sum(eco_ha))::numeric, 0) aspectcwise,
       round((sum(albedodry_l::float * eco_ha)/sum(eco_ha))::numeric, 0) albedodry_l, 
       round((sum(albedodry_r::float * eco_ha)/sum(eco_ha))::numeric, 0) albedodry_r, 
       round((sum(albedodry_h::float * eco_ha)/sum(eco_ha))::numeric, 0) albedodry_h, 
       round((sum(airtempa_l::float * eco_ha)/sum(eco_ha))::numeric, 0) airtempa_l, 
       round((sum(airtempa_r::float * eco_ha)/sum(eco_ha))::numeric, 0) airtempa_r, 
       round((sum(airtempa_h::float * eco_ha)/sum(eco_ha))::numeric, 0) airtempa_h, 
       round((sum(map_l::float * eco_ha)/sum(eco_ha))::numeric, 0) map_l,
       round((sum(map_r::float * eco_ha)/sum(eco_ha))::numeric, 0) map_r, 
       round((sum(map_h::float * eco_ha)/sum(eco_ha))::numeric, 0) map_h, 
       round((sum(reannualprecip_l::float * eco_ha)/sum(eco_ha))::numeric, 0) reannualprecip_l, 
       round((sum(reannualprecip_r::float * eco_ha)/sum(eco_ha))::numeric, 0) reannualprecip_r, 
       round((sum(reannualprecip_h::float * eco_ha)/sum(eco_ha))::numeric, 0) reannualprecip_h, 
       round((sum(ffd_l::float * eco_ha)/sum(eco_ha))::numeric, 0) ffd_l, 
       round((sum(ffd_r::float * eco_ha)/sum(eco_ha))::numeric, 0) ffd_r,
       round((sum(ffd_h::float * eco_ha)/sum(eco_ha))::numeric, 0) ffd_h, 
       round((sum(cropprodindex::float * eco_ha)/sum(eco_ha))::numeric, 0) cropprodindex, 
       round((sum(rsprod_l::float * eco_ha)/sum(eco_ha))::numeric, 0) rsprod_l,
       round((sum(rsprod_r::float * eco_ha)/sum(eco_ha))::numeric, 0) rsprod_r, 
       round((sum(rsprod_h::float * eco_ha)/sum(eco_ha))::numeric, 0) rsprod_h, 
       round((sum(initsub_l::float * eco_ha)/sum(eco_ha))::numeric, 0) initsub_l, 
       round((sum(initsub_r::float * eco_ha)/sum(eco_ha))::numeric, 0) initsub_r, 
       round((sum(initsub_h::float * eco_ha)/sum(eco_ha))::numeric, 0) initsub_h,
       round((sum(totalsub_l::float * eco_ha)/sum(eco_ha))::numeric, 0) totalsub_l, 
       round((sum(totalsub_r::float * eco_ha)/sum(eco_ha))::numeric, 0) totalsub_r, 
       round((sum(totalsub_h::float * eco_ha)/sum(eco_ha))::numeric, 0) totalsub_h, 
       round((sum(castorieindex::float * eco_ha)/sum(eco_ha))::numeric, 0) castorieindex, 
       round((sum(ph1to1h2o_l::float * eco_ha)/sum(eco_ha))::numeric, 1) ph1to1h2o_l, 
       round((sum(ph1to1h2o_r::float * eco_ha)/sum(eco_ha))::numeric, 1) ph1to1h2o_r, 
       round((sum(ph1to1h2o_h::float * eco_ha)/sum(eco_ha))::numeric, 1) ph1to1h2o_h
  FROM base
 GROUP BY ecogroup, groupname

), cat_sum AS (
SELECT ecogroup, eco_ha,
  	   compname, sum(eco_ha) over(partition by ecogroup, compname) compname_sum,
       runoff, sum(eco_ha) over(partition by ecogroup, runoff) runoff_sum,
       wei, sum(eco_ha) over(partition by ecogroup, wei) wei_sum,
       weg, sum(eco_ha) over(partition by ecogroup, weg) weg_sum,
       erocl, sum(eco_ha) over(partition by ecogroup, erocl) erocl_sum,
       earthcovkind1, sum(eco_ha) over(partition by ecogroup, earthcovkind1) earthcovkind1_sum,
       earthcovkind2, sum(eco_ha) over(partition by ecogroup, earthcovkind2) earthcovkind2_sum,
       hydricon, sum(eco_ha) over(partition by ecogroup, hydricon) hydricon_sum,
       hydricrating, sum(eco_ha) over(partition by ecogroup, hydricrating) hydricrating_sum,
       drainagecl, sum(eco_ha) over(partition by ecogroup, drainagecl) drainagecl_sum,
       geomdesc, sum(eco_ha) over(partition by ecogroup, geomdesc) geomdesc_sum,
       nirrcapcl, sum(eco_ha) over(partition by ecogroup, nirrcapcl) nirrcapcl_sum,
       nirrcapscl, sum(eco_ha) over(partition by ecogroup, nirrcapscl) nirrcapscl_sum,
       nirrcapunit, sum(eco_ha) over(partition by ecogroup, nirrcapunit) nirrcapunit_sum,
       irrcapcl, sum(eco_ha) over(partition by ecogroup, irrcapcl) irrcapcl_sum,
       irrcapscl, sum(eco_ha) over(partition by ecogroup, irrcapscl) irrcapscl_sum,
       irrcapunit, sum(eco_ha) over(partition by ecogroup, irrcapunit) irrcapunit_sum,
       constreeshrubgrp, sum(eco_ha) over(partition by ecogroup, constreeshrubgrp) constreeshrubgrp_sum,
       wndbrksuitgrp, sum(eco_ha) over(partition by ecogroup, wndbrksuitgrp) wndbrksuitgrp_sum,
       foragesuitgrpid, sum(eco_ha) over(partition by ecogroup, foragesuitgrpid) foragesuitgrpid_sum,
       wlgrain, sum(eco_ha) over(partition by ecogroup, wlgrain) wlgrain_sum,
       wlgrass, sum(eco_ha) over(partition by ecogroup, wlgrass) wlgrass_sum,
       wlherbaceous, sum(eco_ha) over(partition by ecogroup, wlherbaceous) wlherbaceous_sum,
       wlshrub, sum(eco_ha) over(partition by ecogroup, wlshrub) wlshrub_sum,
       wlconiferous, sum(eco_ha) over(partition by ecogroup, wlconiferous) wlconiferous_sum,
       wlhardwood, sum(eco_ha) over(partition by ecogroup, wlhardwood) wlhardwood_sum,
       wlwetplant, sum(eco_ha) over(partition by ecogroup, wlwetplant) wlwetplant_sum,
       wlshallowwat, sum(eco_ha) over(partition by ecogroup, wlshallowwat) wlshallowwat_sum,
       wlrangeland, sum(eco_ha) over(partition by ecogroup, wlrangeland) wlrangeland_sum,
       wlopenland, sum(eco_ha) over(partition by ecogroup, wlopenland) wlopenland_sum,
       wlwoodland, sum(eco_ha) over(partition by ecogroup, wlwoodland) wlwoodland_sum,
       wlwetland, sum(eco_ha) over(partition by ecogroup, wlwetland) wlwetland_sum,
       soilslippot, sum(eco_ha) over(partition by ecogroup, soilslippot) soilslippot_sum,
       frostact, sum(eco_ha) over(partition by ecogroup, frostact) frostact_sum,
       hydgrp, sum(eco_ha) over(partition by ecogroup, hydgrp) hydgrp_sum,
       corcon, sum(eco_ha) over(partition by ecogroup, corcon) corcon_sum,
       corsteel, sum(eco_ha) over(partition by ecogroup, corsteel) corsteel_sum,
       taxclname, sum(eco_ha) over(partition by ecogroup, taxclname) taxclname_sum,
       taxgrtgroup, sum(eco_ha) over(partition by ecogroup, taxgrtgroup) taxgrtgroup_sum,
       flecolcomnum, sum(eco_ha) over(partition by ecogroup, flecolcomnum) flecolcomnum_sum,
       flhe, sum(eco_ha) over(partition by ecogroup, flhe) flhe_sum,
       flphe, sum(eco_ha) over(partition by ecogroup, flphe) flphe_sum,
       flsoilleachpot, sum(eco_ha) over(partition by ecogroup, flsoilleachpot) flsoilleachpot_sum,
       flsoirunoffpot, sum(eco_ha) over(partition by ecogroup, flsoirunoffpot) flsoirunoffpot_sum,
       fltemik2use, sum(eco_ha) over(partition by ecogroup, fltemik2use) fltemik2use_sum,
       fltriumph2use, sum(eco_ha) over(partition by ecogroup, fltriumph2use) fltriumph2use_sum,
       indraingrp, sum(eco_ha) over(partition by ecogroup, indraingrp) indraingrp_sum,
       innitrateleachi, sum(eco_ha) over(partition by ecogroup, innitrateleachi) innitrateleachi_sum,
       misoimgmtgrp, sum(eco_ha) over(partition by ecogroup, misoimgmtgrp) misoimgmtgrp_sum,
       vasoimgtgrp, sum(eco_ha) over(partition by ecogroup, vasoimgtgrp) vasoimgtgrp_sum,
       texdesc, sum(eco_ha) over(partition by ecogroup, texdesc) texdesc_sum,
       pmgroupname, sum(eco_ha) over(partition by ecogroup, pmgroupname) pmgroupname_sum
  FROM base

), base_cat AS (
SELECT ecogroup,
       (array_agg(compname order by compname_sum DESC))[1] compname,
       (array_agg(runoff order by runoff_sum DESC))[1] runoff,
       (array_agg(wei order by wei_sum DESC))[1] wei,
       (array_agg(weg order by weg_sum DESC))[1] weg,
       (array_agg(erocl order by erocl_sum DESC))[1] erocl,
       (array_agg(earthcovkind1 order by earthcovkind1_sum DESC))[1] earthcovkind1,
       (array_agg(earthcovkind2 order by earthcovkind2_sum DESC))[1] earthcovkind2,
       (array_agg(hydricon order by hydricon_sum DESC))[1] hydricon,
       (array_agg(hydricrating order by hydricrating_sum DESC))[1] hydricrating,
       (array_agg(drainagecl order by drainagecl_sum DESC))[1] drainagecl,
       (array_agg(geomdesc order by geomdesc_sum DESC))[1] geomdesc,
       (array_agg(nirrcapcl order by nirrcapcl_sum DESC))[1] nirrcapcl,
       (array_agg(nirrcapscl order by nirrcapscl_sum DESC))[1] nirrcapscl,
       (array_agg(nirrcapunit order by nirrcapunit_sum DESC))[1] nirrcapunit,
       (array_agg(irrcapcl order by irrcapcl_sum DESC))[1] irrcapcl,
       (array_agg(irrcapscl order by irrcapscl_sum DESC))[1] irrcapscl,
       (array_agg(irrcapunit order by irrcapunit_sum DESC))[1] irrcapunit,
       (array_agg(constreeshrubgrp order by constreeshrubgrp_sum DESC))[1] constreeshrubgrp,
       (array_agg(wndbrksuitgrp order by wndbrksuitgrp_sum DESC))[1] wndbrksuitgrp,
       (array_agg(foragesuitgrpid order by foragesuitgrpid_sum DESC))[1] foragesuitgrpid,
       (array_agg(wlgrain order by wlgrain_sum DESC))[1] wlgrain,
       (array_agg(wlgrass order by wlgrass_sum DESC))[1] wlgrass,
       (array_agg(wlherbaceous order by wlherbaceous_sum DESC))[1] wlherbaceous,
       (array_agg(wlshrub order by wlshrub_sum DESC))[1] wlshrub,
       (array_agg(wlconiferous order by wlconiferous_sum DESC))[1] wlconiferous,
       (array_agg(wlhardwood order by wlhardwood_sum DESC))[1] wlhardwood,
       (array_agg(wlwetplant order by wlwetplant_sum DESC))[1] wlwetplant,
       (array_agg(wlshallowwat order by wlshallowwat_sum DESC))[1] wlshallowwat,
       (array_agg(wlrangeland order by wlrangeland_sum DESC))[1] wlrangeland,
       (array_agg(wlopenland order by wlopenland_sum DESC))[1] wlopenland,
       (array_agg(wlwoodland order by wlwoodland_sum DESC))[1] wlwoodland,
       (array_agg(wlwetland order by wlwetland_sum DESC))[1] wlwetland,
       (array_agg(soilslippot order by soilslippot_sum DESC))[1] soilslippot,
       (array_agg(frostact order by frostact_sum DESC))[1] frostact,
       (array_agg(hydgrp order by hydgrp_sum DESC))[1] hydgrp,
       (array_agg(corcon order by corcon_sum DESC))[1] corcon,
       (array_agg(corsteel order by corsteel_sum DESC))[1] corsteel,
       (array_agg(taxclname order by taxclname_sum DESC))[1] taxclname,
       (array_agg(taxgrtgroup order by taxgrtgroup_sum DESC))[1] taxgrtgroup,
       (array_agg(flecolcomnum order by flecolcomnum_sum DESC))[1] flecolcomnum,
       (array_agg(flhe order by flhe_sum DESC))[1] flhe,
       (array_agg(flphe order by flphe_sum DESC))[1] flphe,
       (array_agg(flsoilleachpot order by flsoilleachpot_sum DESC))[1] flsoilleachpot,
       (array_agg(flsoirunoffpot order by flsoirunoffpot_sum DESC))[1] flsoirunoffpot,
       (array_agg(fltemik2use order by fltemik2use_sum DESC))[1] fltemik2use,
       (array_agg(fltriumph2use order by fltriumph2use_sum DESC))[1] fltriumph2use,
       (array_agg(indraingrp order by indraingrp_sum DESC))[1] indraingrp,
       (array_agg(innitrateleachi order by innitrateleachi_sum DESC))[1] innitrateleachi,
       (array_agg(misoimgmtgrp order by misoimgmtgrp_sum DESC))[1] misoimgmtgrp,
       (array_agg(vasoimgtgrp order by vasoimgtgrp_sum DESC))[1] vasoimgtgrp,
       (array_agg(texdesc order by texdesc_sum DESC))[1] texdesc,
       (array_agg(pmgroupname order by pmgroupname_sum DESC))[1] pmgroupname
  FROM cat_sum
 GROUP BY ecogroup

), wgt_join AS (
SELECT a.*,
       b.compname, b.runoff, b.wei, b.weg, b.erocl, b.earthcovkind1, b.earthcovkind2,
	   b.hydricon, b.hydricrating, b.drainagecl, b.geomdesc, b.nirrcapcl, b.nirrcapscl,
	   b.nirrcapunit, b.irrcapcl, b.irrcapscl, b.irrcapunit, b.constreeshrubgrp,
	   b.wndbrksuitgrp, b.foragesuitgrpid, b.wlgrain, b.wlgrass, b.wlherbaceous,
	   b.wlshrub, b.wlconiferous, b.wlhardwood, b.wlwetplant, b.wlshallowwat,
	   b.wlrangeland, b.wlopenland, b.wlwoodland, b.wlwetland, b.soilslippot,
	   b.frostact, b.hydgrp, b.corcon, b.corsteel, b.taxclname, b.taxgrtgroup, 
	   b.flecolcomnum, b.flhe, b.flphe, b.flsoilleachpot, b.flsoirunoffpot, 
	   b.fltemik2use, b.fltriumph2use, b.indraingrp, b.innitrateleachi, 
	   b.misoimgmtgrp, b.vasoimgtgrp, b.texdesc, b.pmgroupname
  FROM base_real a
  INNER JOIN base_cat b ON a.ecogroup = b.ecogroup
)

SELECT * FROM wgt_join;

